services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      PGDATABASE: avance-database
    depends_on:
      database:
        condition: service_healthy
    secrets:
      - jwt_secret
      - postgres_password
    volumes:
      - ./backend:/avance/backend

  database:
    image: "postgres:14.16-alpine3.20"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    secrets:
      - postgres_password
    environment:
      PGUSER: postgres
      POSTGRES_DB: avance-database
    command: [
      "sh", "-c",
      "export POSTGRES_PASSWORD=$(cat /run/secrets/postgres_password) &&
      docker-entrypoint.sh postgres"
    ]

secrets:
  jwt_secret:
    file: secrets/jwt_secret.txt
  postgres_password:
    file: secrets/postgres_password.txt